// Imports
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'

// Styles
import './globals.css'

// Fonts
const inter = Inter({ subsets: ['latin'] })

// SEO
export const metadata: Metadata = {
  title: 'ATR',
  description: 'Generated by create next app',
}

// Rendering
export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  )
}
